### ISSUE TITLE
Old password have to be checked during change password procedure

### ISSUE THREAD

**Issue by AndreyNick** [AndreyNick/gym3000web#10]
There is the case when user wants to change the password.
He opens the proper page and sees 3 fields:
-Password
-New password
-Repeat new password.
Password field value have to be matched with user.password value from DB.
User.password value was got from user as his password and encrypted by BCryptPasswordEncoder before saving. So, we have to match encrypted password from DB and newly entered, non encrypted password to let user to change password. The point is that after encryption newly entered password I get the value that is different from user's old password. As I checked I receive different values from BCryptPasswordEncoder after encryption the same value. It have to be double checked.
The steps to reproduce the problem are below:
1)Login to the system as a user;
2)Enter to your profile by tapping to the link in the top right corner of the screen. The link is called as your user's name. (url is .../profile);
3)Tap to the link 'Edit password';
4)All fields have to be properly filled and press 'Save'.
AR: The password is changing even if Password field value wasn't equal to old user's password
ER: The password have to be checked. If the password value doesn't match the old user's password a new error message have to be shown: 'error.password.previous_password_incorrect'.
The logic for this case is already provided in com.gym.validator.EditPasswordValidator.

**Comment by overriderb** [comment]
Fixed: [#e69a837](https://github.com/AndreyNick/gym3000web/commit/e69a837cd1433efd427407076b6f82cf66b46e66)
