### ISSUE TITLE
Complete Internationalisation

### ISSUE THREAD

**Issue by AndreyNick** [AndreyNick/gym3000web#5]
There is untranslated parts in the project. It would be great to finish it. Untranslated parts could be found on the pages, when Programs or Exercises lists are empty. 
For example:
`<span class="text">
                    <a><spring:message code="message.no_exercise_templates"/>
                        <br />
                        You can add them <a href="<c:url value="/e_temp_list"/>">here</a></a>
                    <br />
          </span>`
They have to be on <span class="text"> as i remember

**Comment by overriderb** [comment]
looks like, can be closed, Andrey?
